"""
Export evolved champion brains for index.html.

A champion genome is only the *plastic weights* on the frozen scaffold, so to
run it in index.html we rebuild the exact scaffold (build_scaffold, seed 42),
splice the genome into the plastic synapses, and emit each champion's COMPLETE
network — neuron params, positions, and full incoming-synapse lists — in the
shape index.html uses (inc[post] = [{pre, weight, isReflex}, ...]).

Output: breedstock_brains.js  ->  window.BREEDSTOCK_BRAINS = [...]
index.html loads this via <script src> (works under file://, unlike fetch).

Usage:  python3 champion_export.py [champions_json] [out_js]
"""
import sys
import json
import numpy as np

from organoid_simulator import creature_breedstock as bs


def brain_from_genome(ctx, genome):
    """Reconstruct index.html-shaped network state from a plastic-weight genome."""
    net = bs._apply_genome(ctx, np.asarray(genome, dtype=float))
    N = int(net['N'])
    pre, post = net['pre'], net['post']
    weight, is_reflex = net['weight'], net['is_reflex']

    inc = [[] for _ in range(N)]
    for s in range(len(pre)):
        j = int(post[s])
        inc[j].append([int(pre[s]), round(float(weight[s]), 5), bool(is_reflex[s])])

    return dict(
        N=N,
        K=int(net['K']),
        pool=bs.SCAFFOLD,                       # scaffold hyperparams for reference
        types=net['types'].astype(int).tolist(),
        subtypes=net['subtypes'].astype(int).tolist(),
        a=[round(x, 6) for x in net['a'].tolist()],
        b=[round(x, 6) for x in net['b'].tolist()],
        c=[round(x, 4) for x in net['c'].tolist()],
        d=[round(x, 6) for x in net['d'].tolist()],
        px=[round(x, 5) for x in net['px'].tolist()],
        py=[round(x, 5) for x in net['py'].tolist()],
        pz=[round(x, 5) for x in net['pz'].tolist()],
        inc=inc,                                # inc[j] = [[pre, weight, isReflex], ...]
    )


def main():
    champs_path = sys.argv[1] if len(sys.argv) > 1 else 'breedstock_champions.json'
    # Default: land next to index.html (repo root) so it can <script src> it.
    out_path = sys.argv[2] if len(sys.argv) > 2 else '../breedstock_brains.js'

    with open(champs_path) as f:
        store = json.load(f)

    _, ctx = bs.build_scaffold()
    assert ctx['n_genes'] == store['n_genes'], "scaffold/genome mismatch"

    out = []
    for c in store['champions']:
        brain = brain_from_genome(ctx, c['genome'])
        out.append(dict(
            label=(f"Champion #{c['rank']+1}  (gen {c['generation']}, "
                   f"fit {c['fitness']:.2f}, food {c['mean_food']:.1f}, "
                   f"surv {c['mean_survival']:.0f})"),
            rank=c['rank'],
            fitness=c['fitness'],
            mean_food=c['mean_food'],
            mean_survival=c['mean_survival'],
            generation=c['generation'],
            brain=brain,
        ))

    js = "// Auto-generated by champion_export.py — evolved breedstock brains.\n"
    js += "window.BREEDSTOCK_BRAINS = " + json.dumps(out, separators=(',', ':')) + ";\n"
    with open(out_path, 'w') as f:
        f.write(js)

    kb = len(js) / 1024.0
    print(f"wrote {out_path}: {len(out)} champions, {kb:.0f} KB")
    for c in out:
        print("  " + c['label'])


if __name__ == '__main__':
    main()
